# Generated by Django 5.1.7 on 2025-03-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
